### ISSUE TITLE
32-bit EFI support

### ISSUE THREAD

**Issue by Quackdoc** [dahliaOS/releases#11]
**Is your feature request related to a problem? Please describe.**
There are plenty of devices that have support for 64bit cpu and kernel, but only support 32bit efi. I would like to be able to use dahlia on devices such as this. 

currently I need to use grub file manager to manually load the grub.cfg to get dahlia to boot on my device

**Describe the solution you'd like**
Support for 32bit efi 

**Do you have an idea of how we would add it?**
compiling grub with 32bit support

**Why should we add it?**
this would not only increase the ammount of devices dahlia works on, but also help make some of these older devices work longer

**Comment by Erdragh** [comment]
Just bumping this thread to say that I'd like 32-bit efi support too, as many low end devices have a 64bit processor, but only a 32bit efi.

**Comment by nmcain** [comment]
Howdy, this featureset has been added to the next version of Buildroot. Thanks!
