### ISSUE TITLE
xorg can't find display on any hardware I try

### ISSUE THREAD

**Issue by nonetrix** [dahliaOS/releases#5]
**Describe the bug**

**To Reproduce**
1. Go to https://dahliaos.io/
2. Click on download the iso
3. try to boot
4. xorg could not find display

**Expected behavior**
The desktop starts up and looks nice

**Screenshots**
too lazy but it's just text I'll type it out 

(==) Log file: "/var/X11/xorg.conf.d"
(EE)
Fatal server error:
(EE) no screens found(EE)
(EE)
Please consult the The X.Org Foundation support
           at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing the log file.
xinit: unable to connect to X server: Connection refused 
xinit: unexpected signal 2
xauth: error in locking authority file /root/.Xauthority

yes I did just type all of that by hand I could have taken 1000 crappy pictures with my phone or try running in a vm

**Desktop (please complete the following information):**
 - OS: bro I just clicked le download button
 - Device: laptop with Intel Celeron N3160 and 4gbs of ram I also tried my PC with a ryzen 7 3700x and gtx 1080 32gbs of ram samething 

**Smartphone (please complete the following information):**
 - Device: lol what why you want my smart phone can you port to the pinephone or something that would be epic

**Additional context**
I tried booting on real hardware with the Linux version was going to try the weird google kernel thing but I could not find it neofetch say Linux 5.10.1 though so guess it's Linux based

**Comment by nmcain** [comment]
Which system image is this?

**Comment by nonetrix** [comment]
> Which system image is this?

the latest one form the website link is here https://github.com/dahliaOS/releases/releases/download/201215-x86_64/dahliaOS-201215-efi.zip I can give you more info if you need it

**Comment by nonetrix** [comment]
> > Which system image is this?
> 
> the latest one form the website link is here https://github.com/dahliaOS/releases/releases/download/201215-x86_64/dahliaOS-201215-efi.zip I can give you more info if you need it

I'm guessing this is not really made for real hardware but I wanted to try my luck anyway since I was able to get stuff like haiku os to boot off my computer and I just like trying weird things like this

**Comment by nmcain** [comment]
This issue seems to happen erratically on many devices, if you reflash the image, it should boot on the PC with no issue.

**Comment by nonetrix** [comment]
hmm odd I guess I can try flashing form dd instead of cringe gnome disks that

**Comment by nonetrix** [comment]
funny problem.. my sd card just shit itself.. I think these 2 things might be connected.. ;-;

anyway going to find another way of burning the iso

**Comment by nonetrix** [comment]
yeah it was the SD card sorry
