### ISSUE TITLE
consider enabling chromebook drivers in the kernel 

### ISSUE THREAD

**Issue by nonetrix** [dahliaOS/releases#6]
**Is your feature request related to a problem? Please describe.**
DahliaOS works fine on my PC but my corebooted chromebook the keyboard and mouse do not work

**Describe the solution you'd like**
Chromebook drivers to be built into the kernel 

**For which platform is this feature request?**
- Platform: Linux

**Why should we add it?**
Chromebooks are garbage but they are pretty based and red pilled with coreboot tbh

**Comment by nmcain** [comment]
I experienced this issue as well, sadly it seems like these drivers are not part of the stock kernel, @EnderNightLord-ChromeBook can you confirm if it was working on yours a while ago?
![PXL_20201220_003629205](https://user-images.githubusercontent.com/18690588/104827642-cf926480-5814-11eb-8849-ab5ba508d821.jpg)
![PXL_20201220_003421656 MP](https://user-images.githubusercontent.com/18690588/104827643-d1f4be80-5814-11eb-8eae-478c4d5b954f.jpg)

**Comment by nmcain** [comment]
Ok, looking at this, you might be able to sideload the kernel from Gallium Linux into the image for full chrome platform support, but it doesnt look like it will work unless they built it onto 5.9 and newer.

**Comment by nonetrix** [comment]
> Ok, looking at this, you might be able to sideload the kernel from Gallium Linux into the image for full chrome platform support, but it doesnt look like it will work unless they built it onto 5.9 and newer.

no they are in the kernel just have to enable them before compiling 

    Device Drivers  --->
       [*] Platform support for Chrome hardware  --->
           <*> Chrome OS Laptop
           <*> Chrome OS pstore support
           < > ChromeOS Tablet Switch Controller
           < > Backlight LED support for Chrome OS keyboards

source:
https://wiki.gentoo.org/wiki/Acer_Chromebook_C720

**Comment by nmcain** [comment]
afaik I have that enabled in my configuration, let me check.

**Comment by electrikjesus** [comment]
It's a real easy merge from Gallium OS kernel source. Never any conflicts.

**Comment by EnderNightLord-ChromeBook** [comment]
> 
> 
> I experienced this issue as well, sadly it seems like these drivers are not part of the stock kernel, @EnderNightLord-ChromeBook can you confirm if it was working on yours a while ago?
> ![PXL_20201220_003629205](https://user-images.githubusercontent.com/18690588/104827642-cf926480-5814-11eb-8849-ab5ba508d821.jpg)
> ![PXL_20201220_003421656 MP](https://user-images.githubusercontent.com/18690588/104827643-d1f4be80-5814-11eb-8eae-478c4d5b954f.jpg)

Chromebook drivers do not work.. the only thing that really works is the intel graphics

**Comment by EnderNightLord-ChromeBook** [comment]
I suggest that we use our own kernel..

**Comment by gitbucket-crypto** [comment]
For cyan chromebook i have compiled audio drivers but still missing the keyboard and touchscreen.

**Comment by nmcain** [comment]
Who manufactures your touchscreen?

**Comment by puntillol59** [comment]
The CYAN codename is for the Acer chromebook R11. (I own one and it looks like acer manufactured the touchscreen  thenselves.)

**Comment by gitbucket-crypto** [comment]
> The CYAN codename is for the Acer chromebook R11. (I own one and it looks like acer manufactured the touchscreen thenselves.)

No both touchpad and touchscreen is Elan, Arch linux and Fedora recognizes

**Comment by gitbucket-crypto** [comment]
> Who manufactures your touchscreen?

Elan, You can run Arch linux or Fedora they recognizes but ubuntu and debian, they dont offer support for Elantech hardware.

**Comment by EnderNightLord-ChromeBook** [comment]
Weird

**Comment by gitbucket-crypto** [comment]
For Help Acer R11 hardware-info

`INFO

cpu:
Intel® Celeron® CPU N3060 @ 1.60GHz, 1739 MHz
Intel® Celeron® CPU N3060 @ 1.60GHz, 480 MHz
keyboard:
Logitech Unifying Receiver
/dev/input/event3 AT Translated Set 2 keyboard
mouse:
Logitech Unifying Receiver
/dev/input/mice Elan Touchscreen
/dev/input/mice Elan Touchpad
monitor:

AUO LCD Monitor
graphics card:
Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller
sound:
Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series High Definition Audio Controller
network:

wlp2s0 Intel Dual Band Wireless-AC 7265
network interface:
wlp2s0 Ethernet network interface
lo Loopback network interface
disk:

/dev/mmcblk0 Disk
/dev/mmcblk1 Disk
/dev/sda SanDisk Cruzer Blade
partition:
/dev/mmcblk0p1 Partition
/dev/sda1 Partition
/dev/sda2 Partition
/dev/sda3 Partition
usb controller:
Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series USB xHCI Controller
bios:

BIOS
bridge:
Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #1
Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCU
Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series SoC Transaction Register
Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #3
hub:
Linux Foundation 2.0 root hub
Linux Foundation 3.0 root hub
memory:

Main Memory
bluetooth:
Intel Bluetooth Device
unknown:
FPU
DMA controller
PIC
Keyboard controller
Intel Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series Power Management Controller
Serial controller
Realtek HD WebCam

lsw

lspci

00:00.0 Host bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series SoC Transaction Register (rev 35)
00:02.0 VGA compatible controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 35)
00:0b.0 Signal processing controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series Power Management Controller (rev 35)
00:14.0 USB controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series USB xHCI Controller (rev 35)
00:1b.0 Audio device: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series High Definition Audio Controller (rev 35)
00:1c.0 PCI bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #1 (rev 35)
00:1c.2 PCI bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #3 (rev 35)
00:1f.0 ISA bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCU (rev 35)
02:00.0 Network controller: Intel Corporation Wireless 7265 (rev 59)

Vendor: usb 0x046d “Logitech, Inc.”
Device: usb 0xc534 “Unifying Receiver”
Revision: “29.00”
Compatible to: int 0x0200 0x0001 “Generic USB Mouse”
Driver: “usbhid”
Driver Modules: “usbhid”
Speed: 12 Mbps
Module Alias: “usb:v046DpC534d2900dc00dsc00dp00ic03isc01ip02in01”
Driver Info #0:
XFree86 Protocol: explorerps/2
GPM Protocol: exps2
Config Status: cfg=new, avail=yes, need=no, active=unknown
Attached to: #33 (Hub)

37: USB 00.0: 10a00 Hub
[Created at usb.122]
Unique ID: pBe4.xYNhIwdOaa6
Parent ID: MZfG.z6Zn2M1LpN8
SysFS ID: /devices/pci0000:00/0000:00:14.0/usb2/2-0:1.0
SysFS BusID: 2-0:1.0
Hardware Class: hub
Model: “Linux Foundation 3.0 root hub”
Hotplug: USB
Vendor: usb 0x1d6b “Linux Foundation”
Device: usb 0x0003 “3.0 root hub”
Revision: “5.11”
Serial ID: “0000:00:14.0”
Driver: “hub”
Driver Modules: “usbcore”
Module Alias: “usb:v1D6Bp0003d0511dc09dsc00dp03ic09isc00ip00in00”
Config Status: cfg=new, avail=yes, need=no, active=unknown
Attached to: #17 (USB Controller)

39: PS/2 00.0: 10800 Keyboard
[Created at input.226]
Unique ID: 9ui9.+49ps10DtUF
Hardware Class: keyboard
Model: “AT Translated Set 2 keyboard”
Vendor: 0x0001
Device: 0x0001 “AT Translated Set 2 keyboard”
Compatible to: int 0x0211 0x0001
Device File: /dev/input/event3
Device Files: /dev/input/event3, /dev/input/by-path/platform-i8042-serio-0-event-kbd
Device Number: char 13:67
Driver Info #0:
XkbRules: xfree86
XkbModel: pc104
Config Status: cfg=new, avail=yes, need=no, active=unknown

40: PS/2 00.0: 10500 PS/2 Mouse
[Created at input.249]
Unique ID: AH6Q.BCYk6nODy52
Hardware Class: mouse
Model: “Elan Touchscreen”
Device: “Elan Touchscreen”
Compatible to: int 0x0210 0x0000
Device File: /dev/input/mice (/dev/input/mouse0)
Device Files: /dev/input/mice, /dev/input/mouse0, /dev/input/event4, /dev/input/by-path/platform-808622C1:00-event
Device Number: char 13:63 (char 13:32)
Driver Info #0:
Buttons: 0
Wheels: 0
XFree86 Protocol: explorerps/2
GPM Protocol: exps2
Config Status: cfg=new, avail=yes, need=no, active=unknown

41: PS/2 00.0: 10500 PS/2 Mouse
[Created at input.249]
Unique ID: AH6Q.wtWU2JjelDC
Hardware Class: mouse
Model: “Elan Touchpad”
Vendor: 0x04f3
Device: 0x002a “Elan Touchpad”
Compatible to: int 0x0210 0x0001
Device File: /dev/input/mice (/dev/input/mouse1)
Device Files: /dev/input/mice, /dev/input/mouse1, /dev/input/event5, /dev/input/by-path/platform-808622C1:05-event-mouse, /dev/input/by-path/platform-808622C1:05-mouse
Device Number: char 13:63 (char 13:33)
Driver Info #0:
Buttons: 1
Wheels: 0
XFree86 Protocol: explorerps/2
GPM Protocol: exps2
Config Status: cfg=new, avail=yes, need=no, active=unknown

42: None 00.0: 10103 CPU
[Created at cpu.462]
Unique ID: rdCR.j8NaKXDZtZ6
Hardware Class: cpu
Arch: X86-64
Vendor: “GenuineIntel”
Model: 6.76.4 “Intel® Celeron® CPU N3060 @ 1.60GHz”
Features: fpu,vme,de,pse,tsc,msr,pae,mce,cx8,apic,sep,mtrr,pge,mca,cmov,pat,pse36,clflush,dts,acpi,mmx,fxsr,sse,sse2,ss,ht,tm,pbe,syscall,nx,rdtscp,lm,constant_tsc,arch_perfmon,pebs,bts,rep_good,nopl,xtopology,tsc_reliable,nonstop_tsc,cpuid,aperfmperf,tsc_known_freq,pni,pclmulqdq,dtes64,monitor,ds_cpl,vmx,est,tm2,ssse3,cx16,xtpr,pdcm,sse4_1,sse4_2,movbe,popcnt,tsc_deadline_timer,aes,rdrand,lahf_lm,3dnowprefetch,epb,pti,ibrs,ibpb,stibp,tpr_shadow,vnmi,flexpriority,ept,vpid,tsc_adjust,smep,erms,dtherm,ida,arat,md_clear
Clock: 2066 MHz
BogoMips: 3201.33
Cache: 1024 kb
Units/Processor: 16
Config Status: cfg=new, avail=yes, need=no, active=unknown

43: None 01.0: 10103 CPU
[Created at cpu.462]
Unique ID: wkFv.j8NaKXDZtZ6
Hardware Class: cpu
Arch: X86-64
Vendor: “GenuineIntel”
Model: 6.76.4 “Intel® Celeron® CPU N3060 @ 1.60GHz”
Features: fpu,vme,de,pse,tsc,msr,pae,mce,cx8,apic,sep,mtrr,pge,mca,cmov,pat,pse36,clflush,dts,acpi,mmx,fxsr,sse,sse2,ss,ht,tm,pbe,syscall,nx,rdtscp,lm,constant_tsc,arch_perfmon,pebs,bts,rep_good,nopl,xtopology,tsc_reliable,nonstop_tsc,cpuid,aperfmperf,tsc_known_freq,pni,pclmulqdq,dtes64,monitor,ds_cpl,vmx,est,tm2,ssse3,cx16,xtpr,pdcm,sse4_1,sse4_2,movbe,popcnt,tsc_deadline_timer,aes,rdrand,lahf_lm,3dnowprefetch,epb,pti,ibrs,ibpb,stibp,tpr_shadow,vnmi,flexpriority,ept,vpid,tsc_adjust,smep,erms,dtherm,ida,arat,md_clear
Clock: 2480 MHz
BogoMips: 3201.33
Cache: 1024 kb
Units/Processor: 16
Config Status: cfg=new, avail=yes, need=no, active=unknown

44: None 00.0: 10701 Ethernet
[Created at net.126]
Unique ID: VV91.ndpeucax6V1
Parent ID: qru8.umvaSGpyXfC
SysFS ID: /class/net/wlp2s0
SysFS Device Link: /devices/pci0000:00/0000:00:1c.2/0000:02:00.0
Hardware Class: network interface
Model: “Ethernet network interface”
Driver: “iwlwifi”
Driver Modules: “iwlwifi”
Device File: wlp2s0
HW Address: c0:b6:f9:f7:74:7a
Permanent HW Address: c0:b6:f9:f7:74:7a
Link detected: yes
Config Status: cfg=new, avail=yes, need=no, active=unknown
Attached to: #12 (WLAN controller)

45: None 00.0: 10700 Loopback
[Created at net.126]
Unique ID: ZsBS.GQNx7L4uPNA
SysFS ID: /class/net/lo
Hardware Class: network interface
Model: “Loopback network interface”
Device File: lo
Link detected: yes
Config Status: cfg=new, avail=yes, need=no, active=unknow`

**Comment by EnderNightLord-ChromeBook** [comment]
They don't release touch screen drivers, gallium OS has a good touchpad driver though

**Comment by nmcain** [comment]
I've gone ahead and enabled as much as I can in the kernel configuration for the Chrome platform, these changes should be present in the next release.
