### ISSUE TITLE
Terminal is... Weird? (emulator)

### ISSUE THREAD

**Issue by pofdzm** [dahliaOS/releases#7]
Terminal literally does not accepts any command and the text like root@dahliOS disappears if I write anything, it just becomes something like a notepad. It is the latest build (dahliaOS-201215-legacy.iso), I tried it both on qemu and VirtualBox with 2 GB of ram but the same issue. I also played with the ram size but no effect.

![image](https://user-images.githubusercontent.com/63299895/120827137-cc99d580-c563-11eb-9990-b8994c910edf.png)

Also it was lagging a lot, like slow mouse movements, the apps thing at the left bottom opens after 5 seconds when I click it etc.

**Comment by EnderNightLord-ChromeBook** [comment]
This should be fixed in the next release. Though there is an issue with the terminal at this current moment as well, it should be sorted out for when the next release comes out.

**Comment by nmcain** [comment]
This was indeed fixed in the next release.
