### ISSUE TITLE
Inbuilt Touchpad touchpad doesn't work

### ISSUE THREAD

**Issue by ObiKeahloa** [dahliaOS/releases#8]
**Describe the bug**
Once booted the touchpad that is inbuilt on the Acer A515-52K don't seem to work.

**To Reproduce**
1. Boot Dahlia OS (On the specific device)
2. Try using the os with in-built touchpad
3. See error

**Expected behavior**
For the touchpad and keyboard to work.
**Screenshots**
n/a
**Desktop (please complete the following information):**
 - OS: DahliaOS
 - Device: Acer A515-52K

**Comment by MysteriousLog6** [comment]
If of any help they do work in Manjaro Linux.

**Comment by nmcain** [comment]
Does an external keyboard/mouse work?

**Comment by MysteriousLog6** [comment]
> Does an external keyboard/mouse work?

At another home they don't have an external keyboard.

**Comment by MysteriousLog6** [comment]
Ok , nvm keyboard seems to be working but not touchpad.

**Comment by Golem642** [comment]
I have the same problem on my laptop : touchpad and keyboard doesn't work, i need to connect external mouse and external keyboard before booting into dahliaos, or else i can't do anything. I said before because apparently it doesn't work when you plug them in after dahliaos is booted up

**Comment by Khan6872** [comment]
Same error with me I have Acer Chromebook c720 with 4g ram and Mr Chromebox uefi script

**Comment by Khan6872** [comment]
![Uploading ezgif-5-8705390d98.gif…]()

**Comment by nmcain** [comment]
This is a known issue with kernel drivers for the Chrome OS Embedded Controller that has been resolved in the latest version of Buildroot.
